shellcheck applied (thx earnestly) 2019.06.26. 09:20:50

diff --git a/auru b/auru
--- a/auru
+++ b/auru
@@ -10,9 +10,9 @@
 
 threads=10                                  # max nr. of threads
 maxreq=200                                  # Aurweb API limit / max number of requests at same time
-tempdir="/dev/shm/$(basename $0)"           # temp dir
-datadir="${HOME}/.cache/$(basename $0)"     # data dir
-tempfile="${tempdir}/$(basename $0).temp"   # temp file used to save pkg names with issues
+tempdir="/dev/shm/$(basename "$0")"           # temp dir
+datadir="${HOME}/.cache/$(basename "$0")"     # data dir
+tempfile="${tempdir}/$(basename "$0").temp"   # temp file used to save pkg names with issues
 useragent="Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0"
 
 declare -a pacnames_array
@@ -33,7 +33,7 @@ function array_contains () {
     local seeking=$2
     local in=1
     for element in "${!array}"; do
-        if [[ $element == $seeking ]]; then
+        if [[ $element == "$seeking" ]]; then
             in=0
             break
         fi
@@ -52,20 +52,20 @@ function readlines () {
     local N="$1"
     local line
     local rc="1"
-    for i in $(seq 1 $N); do    # Read at most N lines
-        read line               # Try reading a single line
-        if [ $? -eq 0 ]; then
-            echo $line          # Output line
+    for i in $(seq 1 "$N"); do    # Read at most N lines
+        if read -r line; then     # Try reading a single line
+        #~ if [ $? -eq 0 ]; then
+            echo "$line"          # Output line
             rc="0"
         else
             break
         fi
     done
-    return $rc                  # Return 1 if no lines where read
+    return $rc                    # Return 1 if no lines where read
 }
 
 function get_json() {
-    echo "$(curl --silent --connect-timeout 10 --max-time 15 --get "https://aur.archlinux.org/rpc/?v=5&type=info${1}")"
+    curl --silent --connect-timeout 10 --max-time 15 --get "https://aur.archlinux.org/rpc/?v=5&type=info${1}"
 }
 
 function saveissue() {
@@ -74,19 +74,19 @@ function saveissue() {
 }
 
 function proccess_thread() {
-    local orphan
-    local version="$(expac %v "${name}")"
-    local url="$(expac %u "${name}")"
-    local build="$(expac --timefmt=%s %b "${name}")"
+    local orphan version url build Version URL LastModified
+    version="$(expac %v "${name}")"
+    url="$(expac %u "${name}")"
+    build="$(expac --timefmt=%s %b "${name}")"
     echo -ne "${white}${name}${none} ${green}${version}${none}\r"
 
-    local Version=$(echo "${json}" | jq -r ".results[] | select(.Name == \"${name}\") | .Version")
-    local URL="$(echo "${json}" | jq -r ".results[] | select(.Name == \"${name}\") | .URL")"
-    local LastModified="$(echo "${json}" | jq -r ".results[] | select(.Name == \"${name}\") | .LastModified")"
+    Version=$(echo "${json}" | jq -r ".results[] | select(.Name == \"${name}\") | .Version")
+    URL="$(echo "${json}" | jq -r ".results[] | select(.Name == \"${name}\") | .URL")"
+    LastModified="$(echo "${json}" | jq -r ".results[] | select(.Name == \"${name}\") | .LastModified")"
 
     #~ echo "${name} - ${Version} - ${URL} - ${LastModified}"
     array_contains orphans "${name}" && orphan=" - Orphan in Local System" || orphan=""
-    if [ ! -z "${Version}" ]; then
+    if [ -n "${Version}" ]; then
         if [[ "${Version}" = "${version}" || "${Version}" < "${version}" ]]; then
             if [[ "${LastModified}" < "${build}" ]]; then
                 if [ "${URL}" = "${url}" ]; then
@@ -111,7 +111,7 @@ function proccess_thread() {
                     saveissue "${white}${name}${none} ${green}${version}${none} -> ${green}${Version}${none} - Package URL differs from AUR Upstream URL${orphan}"
                 fi
             else
-                saveissue "${white}${name}${none} ${green}${version}${none} -> ${green}${Version}${none}${orphan} - New Tarball Available on AUR - Local Build Date: $(date -d @${build} +'%x %X') / AUR Last Modified: $(date -d @${LastModified} +'%x %X')"
+                saveissue "${white}${name}${none} ${green}${version}${none} -> ${green}${Version}${none}${orphan} - New Tarball Available on AUR - Local Build Date: $(date -d @"${build}" +'%x %X') / AUR Last Modified: $(date -d @"${LastModified}" +'%x %X')"
             fi
         else
             saveissue "${white}${name}${none} ${yellow}${version}${none} -> ${green}${Version}${none} - New Version Available on AUR${orphan}"
@@ -124,14 +124,14 @@ function proccess_thread() {
 function check_chunk() {
     local search name ret
     readarray -t pacnames_array             # read array from input
-    for name in ${pacnames_array[@]}; do 
+    for name in "${pacnames_array[@]}"; do 
         search="${search}&arg[]=${name}"
     done
     json=$(get_json "${search}")
     ret="$(echo "${json}" | jq -r '.type')"
     if [ "${ret}" = "multiinfo" ]; then
     
-        for name in ${pacnames_array[@]}; do 
+        for name in "${pacnames_array[@]}"; do 
             proccess_thread &
             while (( $(jobs | wc -l ) >= "${threads}" )); do
                 #~ echo "<<<< $(jobs | wc -l ) >>>>" #debug
@@ -142,7 +142,7 @@ function check_chunk() {
         #~ echo "..... $(jobs | wc -l ) ....." # debug
     else
         if [ "${ret}" = "error" ]; then
-            local ret="$(echo "${json}" | jq -r '.error')"
+            ret="$(echo "${json}" | jq -r '.error')"
             echo "Aurweb RPC Interface Query Error: ${ret}"
         else
             echo "Unknow Query Error in https://aur.archlinux.org"
@@ -157,17 +157,17 @@ function check_chunk() {
 
 case "$1" in
     -h|--help)
-        echo -e "Usage: $(basename $0) [--help | --reset 'package' | --check]\n"
+        echo -e "Usage: $(basename "$0") [--help | --reset 'package' | --check]\n"
         echo -e "--reset : Reset 'Activity Detected on Upstream Website' message."
         echo -e "          Will obtain an updated html file for 'package'"
         echo -e "--check : Search for issues on installed foreign packages, they are"
         echo -e "          typically packages installed w/ pacman -U"
         echo -e "--help  : This help\n"
-        echo -e "$(basename $0) dependencies: python-html2text, curl, jq, expac, fzf (optional)"
+        echo -e "$(basename "$0") dependencies: python-html2text, curl, jq, expac, fzf (optional)"
         ;;
 
     --reset)
-        if [ ! -z "${2}" ]; then
+        if [ -n "${2}" ]; then
             if url=$(expac '%u' "${2}"); then
                 if curl --silent --connect-timeout 10 --max-time 15 --user-agent "${useragent}" --output "${tempdir}/${2}.html" "${url}"; then
                     mv -f "${tempdir}/${2}.html" "${datadir}/${2}.html"
@@ -180,14 +180,14 @@ case "$1" in
                 echo "${2} Package Not Found"
             fi
         else
-            echo "Use: $(basename $0) --help"
+            echo "Use: $(basename "$0") --help"
         fi
         ;;
 
     --check)
         echo "Checking dependencies..."
         type html2text curl jq expac tee diff wc >/dev/null || exit 1
-        orphans=( $(pacman -Qqdtm 2>/dev/null) )  # get foreign orphans (Typically installed w/ pacman -U)
+        orphans=( "$(pacman -Qqdtm 2>/dev/null)" )  # get foreign orphans (Typically installed w/ pacman -U)
         >"${tempfile}"
         echo "Checking Foreign Packages Upstream..."
         pacman -Qqm | while chunk=$(readlines "${maxreq}"); do
@@ -196,11 +196,10 @@ case "$1" in
         done
         wait
         type fzf &>/dev/null && [ -s "${tempfile}" ] && \
-            cat "${tempfile}" | \
             fzf --preview-window right:70% \
                 --preview "cat ${datadir}/{}.diff 2>/dev/null ; echo ; pacman -Qil {}" \
                 --layout=reverse \
-                --bind "enter:execute((cat ${datadir}/{}.diff 2>/dev/null ; echo ; pacman -Qil {}) | less),right:toggle-preview-wrap,ctrl-r:execute($0 --reset {})"
+                --bind "enter:execute((cat ${datadir}/{}.diff 2>/dev/null ; echo ; pacman -Qil {}) | less),right:toggle-preview-wrap,ctrl-r:execute($0 --reset {})" < "${tempfile}"
 
         rm -f "${tempfile}" &>/dev/null
         ;;
@@ -213,3 +212,20 @@ esac
 #~ url=$(sed -n 's/^url=//p' "${1}")
 #~ url="${url//[\(\)\'\"]/}"
 #~ echo "$url"
+
+
+#~ 08:19:18 earnestly semeion: You can get thread count with `nproc`.  Don't use $0, don't use basename/dirname when you can use brace expansions.  Don't fake the user agent, use something
+                   #~ identifiable.  I would say don't hardcode ansi escapes, use tput instead, but I'm not actually that bothered, tput is better though.  Don't use 'function'.  Quote
+                   #~ expansions properly, see `shellcheck'.  If you're going to use bash, use bash
+#~ 08:19:21 earnestly and not sh.  Don't use echo, use printf instead.  < will do string comparion, -lt will do numeric.  `shellcheck' should cover the rest of the errors
+#~ 08:19:32 earnestly semeion: But ultimately a tool already exists, called aurphan (for aur packages specifically)                                                       
+#~ 08:19:39 sauyon hullo, I've been trying to get gpg-agent using a Yubikey to work for SSH but keep running into `agent refused operation`
+#~ 08:19:49 <-- caveman (~caveman@cave.mn) has quit (Client Quit)                                                                          
+#~ 08:20:00 --> caveman (~caveman@cave.mn) has joined #archlinux 
+#~ 08:20:05 sauyon `ssh-add -l` lists my key but for some reason `gpg --card-status` errors
+#~ 08:20:33 earnestly semeion: Keep in mind that foreign packages do not mean -U, it means the package doesn't exist in a sync database (this can happen if packages are removed from sync
+                   #~ databases, or added)
+#~ 08:20:45 sauyon sometimes I can replug my device and get the opposite to be true as well
+#~ 08:20:55 <-- Xiti (~Xiti-@unaffiliated/xiti) has quit (Ping timeout: 245 seconds)       
+#~ 08:21:13 <-- mcquinn (~Thunderbi@host186-2.natpool.mwn.de) has quit (Quit: mcquinn)
+#~ 08:21:17 earnestly semeion: Also if you want to check for updates specifically, ignoring all the orphan themes, I think aurutils will have plumbing tools to do just that
